---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-case-conflict

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.5.3
      hooks:
          - id: gitleaks

    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place]

    - repo: https://github.com/thlorenz/doctoc
      rev: v2.2.0 # substitute a tagged version
      hooks:
          - id: doctoc

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.27.1
      hooks:
          - id: yamllint
            args: [-c, .yamllint-config.yaml, --format, parsable, --no-warnings]
