---
name: docker_image
on:
    push:
        branches:
            - main

jobs:
    maven_build:
        uses: ./.github/workflows/maven_build.yaml

    docker:
        runs-on: ubuntu-latest
        needs: [maven_build]
        environment: development
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Download mvn package
              uses: actions/download-artifact@v3
              with:
                  name: maven-artifact
                  path: ./
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: nicojahn/tdengine-kafka-connector:latest
